### ISSUE TITLE
Formula not getting pillar's values

### ISSUE THREAD

**Issue by eughenio** [saltstack-formulas/golang-formula#1]
Hi,

I tried to change the go_path by pillar and didn't work. 

My pillar:

``` YAML
golang:
  lookup:
    version: 1.6
    go_path: /opt
```

The go_path was exchanged only when I did the change in the golang/golang/defaults.yaml.
